### ISSUE TITLE
Add a toggle action to the status bar

### ISSUE THREAD

**Issue by zzhaolei** [ArturoDent/read-only-non-workspace#1]
Maybe we could display an icon in the status bar to quickly toggle read-only status.

like [this](https://github.com/alefragnani/vscode-read-only-indicator):
<img width="287" alt="image" src="https://github.com/ArturoDent/read-only-non-workspace/assets/17561793/98a89d8b-363b-4c6e-b455-e4b00836e196">

**Comment by ArturoDent** [comment]
I like it.  Is it okay to only use the English characters `R O W` for the button?  Not sure how to internationalize it.

**Comment by zzhaolei** [comment]
You can also use icons, like [this](https://github.com/microsoft/vscode-icons):

<img width="64" alt="image" src="https://github.com/ArturoDent/read-only-non-workspace/assets/17561793/337da8d6-d588-480c-9e4b-b5a1351c42ad">

**Comment by ArturoDent** [comment]
With v0.3.1 I have added a toggle action item to the Status Bar.  Let me know if it works for you.  Thanks.

**Comment by zzhaolei** [comment]
Inconsistent icons:
<img width="399" alt="image" src="https://github.com/ArturoDent/read-only-non-workspace/assets/17561793/9dc1f395-0fae-49ce-b58b-54e8edf5c455">

I previously tried to implement the ability to toggle read-only status via the status bar, but failed because VSCode lacks an API to read the read-only state of the active editor.

The current API cannot implement this function correctly.

**Comment by ArturoDent** [comment]
Well it depends on how you define the StatusBarItem - should it show what action it performs or should it show the current state of the file.  I chose to have it show what it would do, i.e., when a file is locked/read-only then the button will unlock it.  And vice-versa.  I could easily swap the text of the StatusBarItem and have it sync the way you want but I think I prefer it the way I have it but I am not sure.

It isn't a mere indicator it is an action button.  Should an action show the current state or what its action is.  I suppose it could just say "Toggle R/O status" and that would be simple as there would be no need to switch the text/icon.

The tab icon IS just an indicator of status, it isn't a clickable action button.

What do you think?

**Comment by zzhaolei** [comment]
> The tab icon IS just an indicator of status, it isn't a clickable action button.

If it is not operable, I think it should not exist in the status bar, the lock icon of vscode is enough.

> Well it depends on how you define the StatusBarItem - should it show what action it performs or should it show the current state of the file. I chose to have it show what it would do, i.e., when a file is locked/read-only then the button will unlock it. And vice-versa. I could easily swap the text of the StatusBarItem and have it sync the way you want but I think I prefer it the way I have it but I am not sure.

I think it is more intuitive to directly display the current status.

For example, if the current file is locked, the status bar item will display R-O LOCK, and clicking the status bar item can switch to R-O UNLOCK. (This is what Jetbrains Idea does)

**Comment by ArturoDent** [comment]
"The tab icon IS just an indicator of status, it isn't a clickable action button."  The tab is a reference to the editor tab, not the StatusBar.

It should really say R-O LOCKED or R-O UnLOCKed if it were to display the current status.

**Comment by zzhaolei** [comment]
Ha, sorry, I misunderstood😬

**Comment by ArturoDent** [comment]
I modified the icon and text in the latest version 0.3.2, see if you like it better.

**Comment by zzhaolei** [comment]
Not bad, the description is clear.👍
